	INTEGER NUMEMP(3),NUM,TEMEMP(3),TEMP
	OPEN(1,FILE='empre.dat',STATUS='old')
	TEMEMP = 999
50	CONTINUE
	READ(1,10)NUM,TEMP
10	FORMAT(I3,4X,I3)
	IF(NUM.EQ.0.AND.TEMP.EQ.0)GOTO 100
	IF(TEMP.LT.TEMEMP(1))THEN
		TEMEMP(3) = TEMEMP(2)
		TEMEMP(2) = TEMEMP(1)
		TEMEMP(1) = TEMP
		NUMEMP(3) = NUMEMP(2)
		NUMEMP(2) = NUMEMP(1)
		NUMEMP(1) = NUM
	ELSE
		IF(TEMP.LT.TEMEMP(2))THEN
			TEMEMP(3) = TEMEMP(2)
			TEMEMP(2) = TEMP
			NUMEMP(3) = NUMEMP(2)
			NUMEMP(2) = NUM
		ELSE
			IF(TEMP.LT.TEMEMP(3))THEN
				TEMEMP(3) = TEMP
				NUMEMP(3) = NUM
			END IF
		END IF
	END IF
	GOTO 50
100	CONTINUE
	WRITE(*,20)NUMEMP(1),TEMEMP(1)
	WRITE(*,20)NUMEMP(2),TEMEMP(2)
	WRITE(*,20)NUMEMP(3),TEMEMP(3)
20	FORMAT('EMPREGADO ',I3,1X,'TRABALHA A',I3,1X,'MESES.')
	STOP
	END