	INTEGER BOIS,GORDO,MAGRO,NUM,UE,US
	REAL MAIOR,NENOR,PESO
	UE = 5
	US = 6
	BOIS = 0
	MAIOR = 0.0
	MENOR = 100000.0
10	IF (BOIS.EQ.9) GO TO 20
		READ(UE,11) NUM,PESO
11		FORMAT(I2,F5.1)
		IF (PESO.GT.MAIOR) THEN
			MAIOR = PESO
			GORDO = NUM
		END IF
		IF (PESO.LT.MENOR) THEN
			MENOR = PESO
			MAGRO = NUM
		END IF
		BOIS = BOIS + 1
	GO TO 10
20	CONTINUE
	WRITE(US,22) GORDO,MAIOR
22	FORMAT(1X,'O BOI MAIS GORDO E O DE NUMERO ',I5,' COM ',
     &       F8.3,'KG'/)
	WRITE(US,24) MAGRO,MENOR
24	FORMAT(1X,'O BOI MAIS MAGRO E O DE NUMERO ',I5,' COM ',
     &       F8.3,'KG'/)
	STOP
	END