C		DECLARAÇÃO DAS VARIÁVEIS
	INTEGER D(100,100),DA(100),ANT(100)
	LOGICAL EXPA(100)
	INTEGER N,DESTIN,ORIGEM,I,J,C,NOVADA,MIN
	INTEGER UE,US
	UE = 5
	US = 6
	open(unit = 24,file='dis_cidades.txt',status='old')
	READ(24,1) N
1	FORMAT(I3)
	do 8 I = 1,N,1
8	READ(24,3) (D(I,J),J=1,N,1)
3	FORMAT(6(I3,2X))
	WRITE(US,2) ((D(I,J), J=1,N), I=1,N)
2	FORMAT(1H ,6(6(I4,2X)/))
	READ(UE,5) ORIGEM,DESTIN
5	FORMAT(I3,2X,I3)
	WRITE(US,4) ORIGEM, DESTIN
4	FORMAT(1H ,I3,2X,I3)
	DO 10 I = 1,N,1
		EXPA(I) = .FALSE.
		DA(I) = 10000
10	CONTINUE
	C = ORIGEM
	DA(C) = 0
20	IF(C.EQ.DESTIN .OR. C.EQ.0) GOTO 50
C		EXPANSÃO DE C
		DO 30 I = 1,N,1
			IF(D(C,I).NE.0 .AND. (.NOT.EXPA(I))) THEN
				NOVADA = DA(C) + D(C,I)
				IF(NOVADA.LT.DA(I)) THEN
					DA(I) = NOVADA
					ANT(I) = C
				END IF
			END IF
30		CONTINUE
		EXPA(C) = .TRUE.
C		DETERMINAÇÃO DO PRÓXIMO C
		MIN = 10000
		C = 0
		DO 40 I = 1,N,1
			IF((.NOT.EXPA(I)) .AND. (DA(I).LT.MIN)) THEN
				MIN = DA(I)
				C = I
			END IF
40		CONTINUE
	GO TO 20
50	CONTINUE
	IF (C.EQ.DESTIN) THEN
C		DESCRICAO DO CAMINHO MINIMO
60	CONTINUE
		WRITE(US,62) C
62		FORMAT(1H ,8X,I2)
		IF (C.EQ.ORIGEM) GO TO 70
		C = ANT(C)
		GO TO 60
	ELSE
		WRITE(US,64)
64		FORMAT(1H1,'NAO EXISTE CAMINHO UNINDO AS DUAS CIDADES')
	END IF
70	CONTINUE
	STOP
	END