C	DECLARACAO DAS VARIAVEIS
	INTEGER PC(151),CN(221),I,J
C	PC - MATRICULAS ALUNOS DE PROGRAMACAO DE COMPUTADORES
C	CN - MATRICULAS ALUNOS DE CALCULO NUMERICO
C	I,J - INDICES
	UE = 5
	US = 6
C	LEITURA DA MATRICULA DOS ALUNOS QUE ESTAO CURSANDO PC
	I = 1
10	CONTINUE
	READ(UE,11) PC(I)
11	FORMAT(I4)
	IF(PC(I).EQ.9999) GO TO 20
		I = I + 1
		GO TO 10
20	CONTINUE
C	LEITURA DA MATRICULA DOS ALUNOS QUE ESTAO CURSANDO CN
	I = 1
30	CONTINUE
	READ(UE,31) CN(I)
31	FORMAT(I4)
	IF(PC(I).EQ.9999) GO TO 40
		I = I + 1
		GO TO 30
40	CONTINUE
C	VERIFICACAO DA MATRICULA SIMULTANEA EM PC E CN
	I = 1
50	CONTINUE
	IF (PC(I).EQ.9999) GO TO 80
		J = 1
60		CONTINUE
		IF (CN(J).EQ.9999.OR.PC(I).EQ.CN(J)) GO TO 70
			J = J + 1
		GO TO 60
70		CONTINUE
		IF (PC(I).EQ.CN(J)) WRITE(US,72) PC(I)
72		FORMAT(1X,I4)
		I = I + 1
	GO TO 50
80	CONTINUE
	STOP
	END PROGRAM