	INTEGER MEDISC,SODISC,NDISC,APDISC,MLDISC,MEDIA,SOMA,N,APROV,
     *	    MELHOR,ALUNO,NOTA,UE,US
	CHARACTER TURMA*1
	DATA UE,US,SODISC,NDISC,APDISC,MLDISC/5,6,3*0,-1/
10	CONTINUE
	SOMA = 0
	N = 0
	APROV = 0
	MELHOR = -1
20	CONTINUE
	READ(UE,21) TURMA,ALUNO,NOTA
21	FORMAT(A1,I1,I3)
	IF (ALUNO.EQ.0) GO TO 30
		N = N + 1
		IF (NOTA.GE.60) THEN
			APROV = APROV + 1
		END IF
		IF (NOTA.GT.MELHOR) THEN
			MELHOR = NOTA
		END IF
		SOMA = SOMA + NOTA
		GO TO 20
30	CONTINUE
	MEDIA = SOMA/N
	WRITE(US,32) TURMA,APROV,MEDIA,MELHOR
32	FORMAT(5X,'TURMA ',A1,5X,'APROVADOS = ',I3,5X,'MEDIA = ',I3,5X,
     *	   'MELHOR NOTA = ',I3,/)
	SODISC = SODISC + SOMA
	NDISC = NDISC + N
	APDISC = APDISC + APROV
	IF (MELHOR.GT.NDISC) THEN
		MLDISC = MELHOR
	END IF
	IF (TURMA.NE.'R') GO TO 10
	MEDISC = SODISC/NDISC
	WRITE(US,34) APDISC,MEDISC,MLDISC
34	FORMAT(5X,'APROVADOS NA DISCIPLINA = ',I3,5X,'MEDIA NA DISCIPINA'
     *	  ' = ',I3/5X,'MELHOR NOTA NA DISCIPLINA = ',I3)
	STOP
	END