	INTEGER CONTA, UE, UES
	REAL SALDO
	CHARACTER*30 CLIENTE
	UE = 2
	UES = 0
	OPEN(UES,FILE='CON')
	OPEN(UE,FILE='CC.TXT',STATUS='OLD',ACCESS='DIRECT',
     *	 FORM='FORMATTED',RECL=38)
10	CONTINUE
C		LEITURA DO Nº DA CONTA
	WRITE(UES,11)
11	FORMAT(1X,'CONTA?')
	READ(UES,13,END=30) CONTA
13	FORMAT(I6)
C		LEITURA DOS DADOS DO ARQUIVO
	READ(UE,15,REC=CONTA,ERR=20) CLIENTE, SALDO
15	FORMAT(A30,F8.2)
	WRITE(UES,16) CONTA,CLIENTE,SALDO
16	FORMAT(1X,'CONTA',I6,/
     *	   1X,'CLIENTE:',A30,/
     *	   1X,'SALDO:',F8.2)
	GO TO 10
20	CONTINUE
		WRITE(UES,21)
21		FORMAT(1X,'NUMERO DA CONTA NAO EXISTE')
	GO TO 10
30	STOP
	END