c	DEFINIÇÃO DO TIPO DAS VARIAVEIS
	REAL TABELA(5,3)
	REAL IMPOST , MULTA
	CHARACTER IDENTI * 5
	INTEGER MESEAT
	INTEGER UE , US , I , J
	
	UE = 5
	US = 6

	READ(UE,1)((TABELA(I,J),J=1,3,1),I= 1,5,1)
1	FORMAT(3(F8.1,2X))

10	CONTINUE
	
		READ(UE,11)IDENTI,IMPOST,MESEAT
11		FORMAT(A5,1X,F8.0,2X,I4)
		IF(IDENTI.EQ.'VAZIO') GOTO 40

C	CALCULO DA MULTA

	I = 6

20	CONTINUE
		I = I -1
	IF(IMPOST.GE.TABELA(I,1).OR.I.EQ.1)GOTO 30
	GOTO 20

30	CONTINUE

	IF(IMPOST.GE.TABELA(I,1))MULTA = TABELA(I,3)*IMPOST/100*MESEAT
	
C	ESCRITA DOS RESULTADOS OBTIDOS
	
	WRITE(US,32)IDENTI,MULTA
32	FORMAT(1H0,A5,2X,F8.0)
	
	GOTO 10
40	CONTINUE

	STOP
	END				
