C		DECLARACAO DAS VARIAVEIS
	INTEGER ESTOQU(101),CODIGO(101)
	INTEGER CLIENT,I,MERCAD,N,QUANTI
	INTEGER UE,US
	UE = 5
	US = 6
C		LEITURA E ESCRITA DO ESTOQUE INICIAL
	WRITE(US,2)
2	FORMAT(1H1,'CODIGO',7X,'ESTOQUE INICIAL')
	I = 1
10	CONTINUE
		READ(UE,11)CODIGO(I),ESTOQU(I)
11		FORMAT(I4,2X,I4)
		IF(CODIGO(I).EQ.9999) GO TO 20
		WRITE(US,12)CODIGO(I),ESTOQU(I)
12		FORMAT(1H ,I4,7X,I4)
		I = I + 1
	GO TO 10
20	CONTINUE
	N = I - 1
30	CONTINUE
		READ(UE,31)CLIENT,MERCAD,QUANTI
31		FORMAT(I4,1X,I4,2X,I4)
		IF(CLIENT.EQ.9999) GO TO 60
C		VERIFICACAO DA EXISTENCIA DA MERCADORIA
		I = 0
40		CONTINUE
			I = I + 1
			IF(I.EQ.N.OR.MERCAD.EQ.CODIGO(I)) GO TO 50
			GO TO 40
50		CONTINUE
		IF(MERCAD.EQ.CODIGO(I)) THEN
			IF(ESTOQU(I).GE.QUANTI) THEN
				ESTOQU(I) = ESTOQU(I) - QUANTI
				WRITE(US,52)CLIENT,MERCAD,QUANTI
52				FORMAT(1H ,I4,'MERCADORIA :',I4,
     1			' PEDIDO ATENDIDO PARA : ',I4,' UNIDADES ')
			ELSE
				WRITE(US,54) CLIENT,MERCAD
54				FORMAT(1H ,'MERCADORIA: ',I4,
     1				' ESTOQUE INSUFICIENTE')
			END IF
		ELSE
			WRITE(US,56)CLIENT,MERCAD
56			FORMAT(1H ,I4,'MERCADORIA: ',I4,
     1			' NAO EXITE A MERCADORIA PEDIDA')
		END IF
	GO TO 30
60	CONTINUE
C		ESCRITA DO ESTOQUE FINAL
	WRITE(US,62)
62	FORMAT(1H ,'CODIGO',7X,'ESOQUE FINAL ')
	DO 70 I = 1,N,1
		WRITE(US,64)CODIGO(I),ESTOQU(I)
64		FORMAT(1H0,2X,I4,7X,I4)
70	CONTINUE
	STOP
	END